#default port where the service will be started
server:
  port: 8085  

#tells about the Eureka server details and its refresh time 
eureka:     
  instance:
    preferIpAddress: true 
  #client:
    serviceUrl:
      # localhost
        defaultZone: http://localhost:8761/eureka/
      # docker
      # defaultZone: http://sa-discovery:8761/eureka/
   # healthcheck:
    #  enabled: true
    #lease:
    #  duration: 5

spring:   
  application:
    name: sa-user   #service defined in gateway
     
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc. 

   
#logging:
#  level:
#    com.sa.displayvideo: DEBUG

